function createStatisticsPanel()

    global TXT_BEAT;
    global TXT_CLASS;
    global TXT_SAMPLES;
    global TXT_MAX;
    global TXT_MIN;
    global TXT_MEAN;
    global TXT_STD;
    global TXT_DOM_FREQ;

    //-----------------------------------
    // Statistics Frame
    //-----------------------------------

    uicontrol(...
        "style","frame",...
        "position",[220 56 840 160]);

    //-----------------------------------
    // Title
    //-----------------------------------

    uicontrol(...
        "style","text",...
        "string","Signal Statistics",...
        "fontsize",15,...
        "fontweight","bold",...
        "horizontalalignment","center",...
        "position",[500 175 280 25]);

    //-----------------------------------
    // First Row
    //-----------------------------------

    TXT_BEAT = uicontrol(...
        "style","text",...
        "position",[250 135 170 25],...
        "horizontalalignment","left",...
        "string","Beat :");

    TXT_CLASS = uicontrol(...
        "style","text",...
        "position",[450 135 170 25],...
        "horizontalalignment","left",...
        "string","Class :");

    TXT_SAMPLES = uicontrol(...
        "style","text",...
        "position",[650 135 170 25],...
        "horizontalalignment","left",...
        "string","Samples :");

    TXT_MAX = uicontrol(...
        "style","text",...
        "position",[850 135 180 25],...
        "horizontalalignment","left",...
        "string","Maximum :");

    //-----------------------------------
    // Second Row
    //-----------------------------------

    TXT_MIN = uicontrol(...
        "style","text",...
        "position",[250 95 170 25],...
        "horizontalalignment","left",...
        "string","Minimum :");

    TXT_MEAN = uicontrol(...
        "style","text",...
        "position",[450 95 170 25],...
        "horizontalalignment","left",...
        "string","Mean :");

    TXT_STD = uicontrol(...
        "style","text",...
        "position",[650 95 170 25],...
        "horizontalalignment","left",...
        "string","Std Dev :");

    TXT_DOM_FREQ = uicontrol(...
        "style","text",...
        "position",[850 95 200 25],...
        "horizontalalignment","left",...
        "string","Dominant Frequency : --");

endfunction
