function createControlPanel()

// Button Size
buttonWidth  = 170;
buttonHeight = 35;

//====================================================
// LEFT PANEL
//====================================================

xLeft = 20;
y = 575;

//---------------- FILE ----------------//

uicontrol(...
"style","text",...
"string","FILE",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xLeft y 170 25]);

y = y-40;

uicontrol("style","pushbutton",...
"string","Open CSV",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","openCsvCallback()");

//---------------- NAVIGATION ----------------//

y = y-65;

uicontrol(...
"style","text",...
"string","NAVIGATION",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xLeft y 170 25]);

y = y-40;

uicontrol("style","pushbutton",...
"string","Next Beat",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","nextBeatCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Previous Beat",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","previousBeatCallback()");

//---------------- VIEW ----------------//

y = y-65;

uicontrol(...
"style","text",...
"string","VIEW",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xLeft y buttonWidth buttonHeight]);

y = y-40;

uicontrol("style","pushbutton",...
"string","Zoom In",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","zoomInCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Zoom Out",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","zoomOutCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Reset Zoom",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","resetZoomCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Pan Left",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","panLeftCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Pan Right",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","panRightCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Reset Plot",...
"position",[xLeft y buttonWidth buttonHeight],...
"callback","resetPlotCallback()");


//====================================================
// RIGHT PANEL
//====================================================

xRight = 1090;
y = 575;

//---------------- ANALYSIS ----------------//

uicontrol(...
"style","text",...
"string","ANALYSIS",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xRight y 170 25]);

y = y-40;

uicontrol("style","pushbutton",...
"string","FFT Analysis",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","fftCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Peak Detection",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","peakDetectionCallback()");

//---------------- FILTERS ----------------//

y = y-65;

uicontrol(...
"style","text",...
"string","FILTERS",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xRight y 170 25]);

y = y-40;

uicontrol("style","pushbutton",...
"string","Moving Average",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","movingAverageCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Median Filter",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","medianFilterCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","Low-pass Filter",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","lowpassFilterCallback()");

y = y-45;

uicontrol("style","pushbutton",...
"string","High-pass Filter",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","highpassFilterCallback()");

//---------------- TOOLS ----------------//

y = y-65;

uicontrol(...
"style","text",...
"string","TOOLS",...
"fontsize",14,...
"fontweight","bold",...
"horizontalalignment","center",...
"position",[xRight y 170 25]);

y = y-40;

// Export Plot
uicontrol("style","pushbutton",...
"string","Export Plot",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","exportPlotCallback()");

y = y-45;

// Export CSV
uicontrol("style","pushbutton",...
"string","Export CSV",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","exportCallback()");

y = y-45;

// Exit
uicontrol("style","pushbutton",...
"string","Exit",...
"position",[xRight y buttonWidth buttonHeight],...
"callback","close(gcf())");

endfunction
